name: docker

on:
  push:
    branches:
      - 'master'
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Collect build context
        id: context
        run: |
          echo "version=$(< VERSION)" >> "$GITHUB_OUTPUT"

      - name: Docker metadata mapping
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ github.repository_owner }}/monero
            ghcr.io/${{ github.repository_owner }}/monero
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/master' }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            MONERO_TAG=${{ steps.context.outputs.version }}
